### ISSUE TITLE
[Question] Device Information

### ISSUE THREAD

**Issue by SteffenGorenflo** [locator-kn/android-app#1]
We need device information of each device in backend. What kind of information can you provide?

We need (at least) the following:
 -  An ID to identify the device
 -  A push ID, used for sending push notifications to the device

**Comment by markusheilig** [comment]
The 'AndroidID' could be used to identify the device (this is a unique 64-bit hex string).
Should be enough to identify a device, right?

For push notifications, each device has to register at Google Cloud Messaging Service, then will get a 'Registration Token'.

**Comment by SteffenGorenflo** [comment]
```js
{
 deviceId: the device identifier,
 type: ios or android,
 version: version of your OS,
 deviceModel: e.g. Galaxy S3 or iPhone 6
}
```
