### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/android-app#11]
![screen shot 2016-03-03 at 2 00 04 nachm](https://cloud.githubusercontent.com/assets/5221667/13495067/b322bfc2-e148-11e5-9c41-cb7613519c62.png)

* Passwort ändern
* Info
    * Datenschutz (wenn geliefert)
    * Nutzungsbedingungen (wenn geliefert)
    * Impressum (wenn geliefert)

**Comment by markusheilig** [comment]
implemented by @Niwonneb by routing the user to the the locator-v1-impressum page.
