### ISSUE TITLE
Heatmap shows no heat-points

### ISSUE THREAD

**Issue by markusheilig** [locator-kn/android-app#5]
Heatmap doesn't show the heatpoints in KN when the user (smartphone) is a few kilometres away from KN.

**Comment by timoweiss** [comment]
I think this is because there are no further queries made once the map is loaded.

**Comment by markusheilig** [comment]
sounds reasonable, but still needs to be fixed :-)

**Comment by timoweiss** [comment]
yesss ;)

**Comment by markusheilig** [comment]
bug is fixed
